services:

  php:
    build: .
    container_name: modulo_clientes_backend
    volumes:
      - ./src:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2.conf:/etc/apache2/apache2.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    entrypoint: ["/entrypoint.sh"]

  db:
    image: mysql:8.0
    container_name: mysql_clientes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modulo_clientes_sedes
      MYSQL_USER: modulo_clientes_sedes
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_clientes
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db